= La Ménardière en poème

A qui s’en sera enquis, Il faudra qu’on réponde : +
Voici une métairie, dans la Vendée profonde. +
“Une métairie dites-vous ? plutôt une seigneurie” +
Eh oui, c’était les deux, du temps que les seigneurs +
N’étaient pas à Versailles à chercher les honneurs.

Nous sommes dans le bocage, c’était un vieux château. +
_(PHOTO Arrière de La Ménardière avec la cour)_ +
Les ans, et puis les guerres, la pluie, les incendies +
Rabattirent sa fierté. Il tomba dans l’oubli. +
Longtemps il attendit que cessent tous ces maux.

Le Puy du Fou, Maillezais, La Chabotterie, Fontenay +
Tour à tour se relèvent, tour à tour se réveillent. +
Usant ses dernières forces, la Ménardière aussi +
Humblement se redresse et doucement reprend vie.

Ses roches de granit couvertes de châtaignes +
Regardent vers le sud, vers l’ombre du dolmen +
Qui rappelait qu’ici toujours on y vécut). +
Le chemin de Saint Pierre, la vieille voie romaine, +
Tout au fond de sa terre est creusée dans les haies.

Et dans le petit bois, le long de l’avenue, +
Dans les douves qui baignent les murs du domaine, +
Dans l’enceinte de la cour, tout  près du puits profond, +
On chasse le chevreuil, on pêche les gardons, +
On cueille les framboises, les roses et les groseilles

*Comme aux temps les plus doux, +
Comme au temps des merveilles*.
